In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# 获取数据文件(已清洗)
data = pd.read_csv(os.path.join(os.getcwd(), 'Datas', 'Data-Cleaning-1.csv'))

# 然后先把连续数值数据标准化
standard_scaler = StandardScaler()
features = data.drop('price', axis=1)
continue_columns = ['symboling', 'normalized-losses', 'volume',
                    'horsepower', 'bore', 'stroke', 'compression-ratio',
                    'peak-rpm', 'highway-mpg', 'engine-size']
features[continue_columns] = standard_scaler.fit_transform(features[continue_columns])

# 给数据插入一列全为1的偏置项权重
features['bias'] = 1

# 再处理分类的数据，one-hot编码
classes_columns = ['make', 'fuel-type', 'aspiration', 'num-of-doors',
                   'body-style', 'drive-wheels', 'engine-location',
                   'engine-type', 'num-of-cylinders', 'fuel-system']
dummies = pd.get_dummies(features[classes_columns])
features = features.join(dummies)
features = features.join(data.price)
features.drop(classes_columns,axis=1,inplace=True)
features.to_csv(os.path.join(os.getcwd(),'Datas','Data-Cleaning-2.csv'),index=False)
features.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>symboling</th>
      <th>normalized-losses</th>
      <th>engine-size</th>
      <th>bore</th>
      <th>stroke</th>
      <th>compression-ratio</th>
      <th>horsepower</th>
      <th>peak-rpm</th>
      <th>highway-mpg</th>
      <th>volume</th>
      <th>...</th>
      <th>num-of-cylinders_three</th>
      <th>num-of-cylinders_twelve</th>
      <th>fuel-system_1bbl</th>
      <th>fuel-system_2bbl</th>
      <th>fuel-system_idi</th>
      <th>fuel-system_mfi</th>
      <th>fuel-system_mpfi</th>
      <th>fuel-system_spdi</th>
      <th>fuel-system_spfi</th>
      <th>price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.78685</td>
      <td>1.336575</td>
      <td>0.045215</td>
      <td>0.513027</td>
      <td>-1.808186</td>
      <td>-0.288273</td>
      <td>0.198569</td>
      <td>-0.213359</td>
      <td>-0.557058</td>
      <td>-1.168294</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>13495.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1.78685</td>
      <td>1.336575</td>
      <td>0.045215</td>
      <td>0.513027</td>
      <td>-1.808186</td>
      <td>-0.288273</td>
      <td>0.198569</td>
      <td>-0.213359</td>
      <td>-0.557058</td>
      <td>-1.168294</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>16500.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.16397</td>
      <td>0.167150</td>
      <td>0.575559</td>
      <td>-2.394827</td>
      <td>0.702918</td>
      <td>-0.288273</td>
      <td>1.334283</td>
      <td>-0.213359</td>
      <td>-0.704134</td>
      <td>-0.422041</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>16500.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.97541</td>
      <td>1.200962</td>
      <td>-0.461021</td>
      <td>-0.517605</td>
      <td>0.480415</td>
      <td>-0.036204</td>
      <td>-0.039139</td>
      <td>0.856208</td>
      <td>-0.115832</td>
      <td>0.169527</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>13950.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.97541</td>
      <td>1.200962</td>
      <td>0.189854</td>
      <td>-0.517605</td>
      <td>0.480415</td>
      <td>-0.540341</td>
      <td>0.304217</td>
      <td>0.856208</td>
      <td>-1.292436</td>
      <td>0.193551</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>17450.0</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 67 columns</p>
</div>