In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv(os.path.join(os.getcwd(), 'Datas', 'Data-Cleaning-2.csv'))
data.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>symboling</th>
      <th>normalized-losses</th>
      <th>engine-size</th>
      <th>bore</th>
      <th>stroke</th>
      <th>compression-ratio</th>
      <th>horsepower</th>
      <th>peak-rpm</th>
      <th>highway-mpg</th>
      <th>volume</th>
      <th>...</th>
      <th>num-of-cylinders_three</th>
      <th>num-of-cylinders_twelve</th>
      <th>fuel-system_1bbl</th>
      <th>fuel-system_2bbl</th>
      <th>fuel-system_idi</th>
      <th>fuel-system_mfi</th>
      <th>fuel-system_mpfi</th>
      <th>fuel-system_spdi</th>
      <th>fuel-system_spfi</th>
      <th>price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.78685</td>
      <td>1.336575</td>
      <td>0.045215</td>
      <td>0.513027</td>
      <td>-1.808186</td>
      <td>-0.288273</td>
      <td>0.198569</td>
      <td>-0.213359</td>
      <td>-0.557058</td>
      <td>-1.168294</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>13495.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1.78685</td>
      <td>1.336575</td>
      <td>0.045215</td>
      <td>0.513027</td>
      <td>-1.808186</td>
      <td>-0.288273</td>
      <td>0.198569</td>
      <td>-0.213359</td>
      <td>-0.557058</td>
      <td>-1.168294</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>16500.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.16397</td>
      <td>0.167150</td>
      <td>0.575559</td>
      <td>-2.394827</td>
      <td>0.702918</td>
      <td>-0.288273</td>
      <td>1.334283</td>
      <td>-0.213359</td>
      <td>-0.704134</td>
      <td>-0.422041</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>16500.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.97541</td>
      <td>1.200962</td>
      <td>-0.461021</td>
      <td>-0.517605</td>
      <td>0.480415</td>
      <td>-0.036204</td>
      <td>-0.039139</td>
      <td>0.856208</td>
      <td>-0.115832</td>
      <td>0.169527</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>13950.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.97541</td>
      <td>1.200962</td>
      <td>0.189854</td>
      <td>-0.517605</td>
      <td>0.480415</td>
      <td>-0.540341</td>
      <td>0.304217</td>
      <td>0.856208</td>
      <td>-1.292436</td>
      <td>0.193551</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>17450.0</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 67 columns</p>
</div>

In [6]:
target = data['price']
features = data.drop('price', axis=1)

In [7]:
# 这里开始划分数据
seed = 123
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=seed)

然后就要开始做梯度的公式了，先看一下目标函数<br>
$J_{(\theta)}=\frac{1}{2m}[(x^0_0*\theta_0+x^0_1*\theta_1+x^0_2*\theta_2+....+x^0_j*\theta_j)+(x^1_0*\theta_0+x^1_1*\theta_1+x^1_2*\theta_2+....+x^1_j*\theta_j)
+(x^2_0*\theta_0+x^2_1*\theta_1+x^2_2*\theta_2+....+x^2_j*\theta_j)+......\qquad+(x^m_0*\theta_0+x^m_1*\theta_1+x^m_2*\theta_2+....+x^m_j*\theta_j)]\\\quad=\frac{1}{2m}[(X^0*\theta^T)+(X^1*\theta^T)+(X^2*\theta^T)+......+(X^m*\theta^T)]$